### ISSUE TITLE
TODO example in Section 13.11 (file 40).

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#10]
The end of Section 13.11 ("Using Reflection to Test Private Methods in Java") contains the code:
```java
// TODO: TEST HERE
```

This example should either be completed or removed.  See `text/40_unit_testing.md`.

**Comment by timparenti** [comment]
It seems this was fixed in 497cbedd400395c182be37f6c0992732df483f9f as part of the chapter split for #11.

Compare:
* https://github.com/laboon/ebook/commit/497cbedd400395c182be37f6c0992732df483f9f#diff-cf34d554273363636a3cf356515bc936L755
* https://github.com/laboon/ebook/commit/497cbedd400395c182be37f6c0992732df483f9f#diff-73a3611a5136a6cfb69f4df2bc9994b2R551

**Comment by laboon** [comment]
That's a half-completed method I accidentally committed.  I'm working on the full version right now.

**Comment by laboon** [comment]
Fixed, and tested to make sure it works, on commit a26bc0e69e85056981da8984295c40ac22c9c965
