### ISSUE TITLE
"Quality analyst" is used only once; perhaps confusing

### ISSUE THREAD

**Issue by shepmaster** [laboon/ebook#107]
> to enter the workforce as a quality analyst

However, everywhere else uses some variant of "quality assurance".

**Comment by timparenti** [comment]
File 5, line 15.

**Comment by shepmaster** [comment]
@timparenti if you are going to provide references, you should include timestamps (aka git hashes). Unfortunately, github doesn't allow directly linking to the source file of a markdown file because of reasons.

**Comment by timparenti** [comment]
@shepmaster With the fairly static structure of the text, the file-and-line number convention has generally been sufficient as a rough pointer.

**Comment by laboon** [comment]
Changed to use "quality assurance" - commit 8ee0f42

**Comment by timparenti** [comment]
"in _the_ quality assurance"?

**Comment by laboon** [comment]
=/ I meant "the field of quality assurance" Fixed in commit 500da59
