### ISSUE TITLE
"money is often saved in the long run" [citation required]

### ISSUE THREAD

**Issue by shepmaster** [laboon/ebook#108]
This is a pretty strong claim, one that I'd like at least a citation (not that I'd follow the citation).

**Comment by timparenti** [comment]
For context, this is in file 10, line 57:

> Interestingly, as more time and resources are spent on fixing defects or improving quality in other ways, money is often saved in the long run.

**Comment by laboon** [comment]
I'm sure I've got some good citations around here somewhere.  Will look them up.

**Comment by laboon** [comment]
I found some references, but nothing definitive.  I am changing it to "may" to avoid making such a strong claim. commit cd48dde
