### ISSUE TITLE
"In this field, a summary of" introduces "fields", inconsistent usage

### ISSUE THREAD

**Issue by shepmaster** [laboon/ebook#110]
Section 6.1.2 — Test Case (or Summary)

> In this field, a summary

What is a field? Field usually implies a software textbox to me, but I could see it meaning the hand-written item. However, this is the only usage of "field" with that meaning in the chapter.

**Comment by laboon** [comment]
Hmm, I thought this would be pretty standard usage (e.g., a field in a form) but I could add a definition.

**Comment by shepmaster** [comment]
I'm not mad if you don't think it's incongruous.

**Comment by laboon** [comment]
I can change it to "section", might be better.

**Comment by laboon** [comment]
365722d in commit

**Comment by laboon** [comment]
What the.. changed in commit 365722d is what I meant to type
