### ISSUE TITLE
"in many organizations, software testers have the power to halt development"

### ISSUE THREAD

**Issue by shepmaster** [laboon/ebook#116]
In my (admittedly small) experience, this has not been true. The best I've seen was "QA could complain really loudly and whoever was above them might listen"

I'd be happy with "in some organizations".

**Comment by timparenti** [comment]
File 13, line 46.

**Comment by laboon** [comment]
Interesting.  In multiple places I've worked, this has been the case - and I've actually discussed this with a couple other QA engineers before writing this line.  The only time it was not so was in smaller companies or places working on software where it quality was not critical.

Let me think about a good compromise.  Maybe "depending on the domain..." or something else as a qualifier?

**Comment by shepmaster** [comment]
In addition, @carols10cents points out that no one can stop developers from developing, but QA could prevent *a release* perhaps.

I'm totally cool with you saying that real companies do this and that my experience has been with the other kind

**Comment by laboon** [comment]
Made some clarifications in commit aee243a  Thanks!
