### ISSUE TITLE
boundary values typo

### ISSUE THREAD

**Issue by dth26** [laboon/ebook#122]
15_testing_basics.md - Interior and Boundary Values

> [MININT, MININT + 1, ... -2, -1] → For input x, outputs -(x)
> [0, 1, ... MAXINT - 1, MAXINT] → For input x, outputs x

> The boundary values are 0 and 1; 

Should be boundary values are -1 and 0

**Comment by laboon** [comment]
Fixed in commit 16cc592e23fa4c42c61e3d6171b6e392bec3c30a
