### ISSUE TITLE
Wrong object name for mocked object

### ISSUE THREAD

**Issue by dth26** [laboon/ebook#123]
41_advanced_unit_testing.md : Mocks and Verification

> public void testHaveFunAtDuckPond() {
> 
>    Person p = new Person();
>    DuckPond dp = Mockito.mock(DuckPond.class);
>    p.haveFunAtDuckPond();
>    verify(duckPond.haveFun(), times(1));
>
> }

should the last line of code be **verify(dp.haveFun(), times(1));**?

**Comment by laboon** [comment]
Yup.  Fixed in commit a1dc6e1
