### ISSUE TITLE
missing "are" on page no 29

### ISSUE THREAD

**Issue by gitLee47** [laboon/ebook#126]
On page 29, 3rd paragraph, last sentence, you missed an "are":
"Note that there other methods of determining what software to build aside from traditional requirements, such as user stories."

should be

"Note that there **are** other methods of determining what software to build aside from traditional requirements, such as user stories."

**Comment by laboon** [comment]
Thanks!  Fixed in commit 757bc5ad97d39da2928caac27136c416d73cf6ff
