### ISSUE TITLE
Repeat word in requirement chapter.

### ISSUE THREAD

**Issue by luizverissimo** [laboon/ebook#128]
i belive that sentece have a repeat word "In our tire air pressure example in the chapter on testing basics, we had some relatively simple requirements, although we did not mention at the time **that that** is what they were:" it is with two "that".

**Comment by timparenti** [comment]
In this case, this is proper English grammar.  The first "that" is subordinating, and the second is adjectival.  http://english.stackexchange.com/a/3426/22525

**Comment by laboon** [comment]
That is correct - although it seems odd, English is an odd language...
