### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by r7y** [laboon/ebook#138]
This is pedantic, and feel free to ignore this, but on page 25, the book says, "Failure cases (also called negative test cases) are cases in which we expect the system to “fail” for some reason, such as attempting to write to a read-only disk, getting the square root of a negative number (in systems that don’t work with imaginary/complex numbers), or attempting to add an invalid username to a system. In failure cases, instead of returning a correct result, the system will do… something else." Integers and real numbers are technically complex numbers, so a calculator that doesn't work with complex numbers at all doesn't sound very realistic. Instead, it could say, "systems that only work with real numbers".
-Skyler Spence

**Comment by laboon** [comment]
True.  Fixed to refer specifically to imaginary numbers in commit eb61761

Please write +1 ISSUE #138 EBOOK on your D3 cover page for one bonus point.

**Comment by r7y** [comment]
Okay, thanks.
