### ISSUE TITLE
Missing word "to" at the end of Test Plans chapter

### ISSUE THREAD

**Issue by BenjaminMuscato** [laboon/ebook#141]
At the very end of the chapter on Test Plans (Chapter 6 in the physical book; located on the repo here: https://github.com/laboon/ebook/blob/master/text/25_test_plans.md), there is a missing word "to".

> "...but said that that test case lined up with the FUN-COFFEE-TOO-HOT requirement, there's no **way tell** just by looking at the traceability matrix"

**Comment by laboon** [comment]
fixed in #142
