### ISSUE TITLE
Code Example Not Formatted

### ISSUE THREAD

**Issue by zachbugay** [laboon/ebook#147]
Code is not formatted on Page 115 of the PDF.

This is in the Advanced Unit Testing chapter. This is right afet testMultiPet5() example. 

![image](https://user-images.githubusercontent.com/5345847/41305179-1d52ef1c-6e40-11e8-99f3-ac2eb0010422.png)

**Comment by laboon** [comment]
This should have been fixed with 57b737be3526e8b929937ee70c624b45d8b47b54 but I need to reinstall xelatex to check.

**Comment by laboon** [comment]
Yes, fixed in that commit.
