### ISSUE TITLE
29_test_plan workthrough boundary values

### ISSUE THREAD

**Issue by ziz19** [laboon/ebook#150]
As the catweight requirement says, the program should only accept positive values, so I wonder if 1 and 0 as boundary values should also be tested. However, it seems like there is only difference between valid and invalid parameter, no boundary tests.

This is a little counter-intuitive to me because previous chapters mention how edge cases can cause issues. I wonder if boundary values matter here; if not, what is reason that we do not care in this case.

**Comment by laboon** [comment]
Since it's a floating-point value, I'd say that our current boundary checking is good enough.  If it were integers, I'd say that this would be a good addition.
