### ISSUE TITLE
Doesn't have a foreward written by someone awesome

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#17]

**Comment by laboon** [comment]
Is that a volunteering I hear?

**Comment by carols10cents** [comment]
maayyyyybbeeeee

**Comment by carols10cents** [comment]
I can't spell foreword though so you might not want to go with me

**Comment by timparenti** [comment]
I wasn't gonna say anything. :wink:

**Comment by laboon** [comment]
I think I'm not going to go with a foreword on the first edition. =/ Next time!

**Comment by timparenti** [comment]
Guess you'll have to move _forward_ without a _foreword_. :wink:
