### ISSUE TITLE
Lack of cohesion at 13:18

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#21]
File 13, line 18 lacks cohesion:

> Remember, though, that a CEO is in charge of an entire corporation, not just engineering, IT or any other particular part.  There's an entire company to run, and even for a tech company, software testing will be a relatively minuscule part of the company in most cases.  There are many other areas asking for resources, often with good reason.  The marketing department is asking for more marketers, and a company that doesn't come up with good ideas for products will fail.  Operations is asking for more help desk personnel; if people can't figure out to use the product, they will stop buying it and the company will fail.  All that being said, there are numerous reasons for that CEO to turn down the project manager's plan.

Is this continuing the argument from the previous paragraph that the CEO should seriously consider cutting testing, or is this offering the more sane contrasting opinion?  If both, consider expanding and splitting into two paragraphs.

**Comment by laboon** [comment]
Addressed and reworded in commit 016efff
