### ISSUE TITLE
Contradiction at 25:53

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#22]
File 25, line 53 has a contradiction:

> In this field, a summary of what the test case is supposed to test, and how, is provided.  In this way, someone reviewing the test case can tell at a glance what is meant to be tested, and sometimes how.  It is usually possible to determine this by a careful examination of the preconditions, input values, and execution steps, but it is usually easier for a human to just read what the test is supposed to do.

"How" to test something is to be provided in the test case summary field, but someone reviewing it can only "sometimes" tell how to test it?

**Comment by laboon** [comment]
This looks to be a leftover from some editing.  Fixed in commit 25eec05a21b1fdbc53278eed381a57d53dece583
