### ISSUE TITLE
1st paragraph of section 2.4 trails off into

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#23]
> If the program does not meet the requirements, or does not operate normally (e.g., crashes randomly, does not respond to normal system

**Comment by timparenti** [comment]
This appears to have been fixed in cc45eff4e59b0a78fbefe6ff6d071a1234dc2f95.

**Comment by timparenti** [comment]
Specifically, https://github.com/laboon/ebook/commit/cc45eff4e59b0a78fbefe6ff6d071a1234dc2f95#diff-a7692c2cef65460d1467395586999da0R59

**Comment by laboon** [comment]
Yup!  Lots of changes today.
