### ISSUE TITLE
Tic Tac Toe is underspecified

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#26]
I'd have my pedantic nerd card revoked if I didn't point out that a tic tac toe board can have BOTH no open squares AND an entire row, column, or diagonal filled in with the same marker, thus leaving an ambiguous case in your specification that currently reads:

> Players shall then take turns placing X’s and O’s (by the first and second player, respectively) in open squares, until there are no open squares (in which case the game is a draw) or an entire row, column, or diagonal are filled in with the same marker, in which case the owner of that marker (X for first player, O for second player) shall be the winner and the other player shall be the loser.

And I'm only 3 pedantry points away from a free coffee.

**Comment by laboon** [comment]
!!! Can't believe I missed this.  Will fix.

**Comment by laboon** [comment]
Fixed in commit e36e812
