### ISSUE TITLE
More unfinished lines.

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#28]
**BEEP BEEP**.  Thanks to @WillEngler for the idea in #19.

I used some serious `pcregrep`-age to find these and sifted through a bunch of false positives, so hopefully (fingers crossed) this is it.

----

File 32, line 39:
> With online systems, oftentimes beta testing can be "mixed in" with regular usage of the system.  You can have a specific subset of users - say, those who have shown an interest in trying new features, or customers important for revenue, or even a random sampling - have access to the new functionality you wish to beta test.  Usually, you want to either clear it with these customers or make sure that they know that the functionality they are using is not considered complete.  You can then **BEEP BEEP**.

File 50, line 118:
> While the previous section described how to ensure code that was testable from a white-box perspective, creating a program that is easily testable from a black-box, systems-level perspective can be even more difficult.  Methods, in general, are meant to be called - there's a built-in interface to do it, and the parameters for each method are generally specified (there are ex **BEEP BEEP**.

File 70, line 37:
> By selecting the most important performance indicators - referred to as __key performance indicators__ or __KPIs__ - you can focus on testing the aspects of performance most important to the users.  This will then allow developers to tune the system to meet the needs of the users, instead of wasting time on parts of the system which the users will not tend to care about, or already have a sufficient level of performance that spending more time on improving it would be a waste of time.  Depending on the level of specificity of the requirements, it may be possible to determine **BEEP BEEP**.

File 98, line 59:
> __Combinatorial testing__: Testing in such a way so as to ensure that various combinations of variables will work as expected.  For example, testing a **BEEP BEEP**.

**Comment by WillEngler** [comment]
:clap::clap:

**Comment by timparenti** [comment]
I see the second one has been addressed in https://github.com/laboon/ebook/commit/f9cc4adb96214a4133732cafc92b057c1c176115#diff-6524b72df863ce7fbbc99ed9f9035979L118.  The others remain.

**Comment by laboon** [comment]
Fixed the other three missing-end sentences in commit 6361a7e
