### ISSUE TITLE
Define "feasible".

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#31]
48a9b8314e64837c00c29d7346f1e46a7ae0dff4 bolded "qualitative" and "feasible" (per @carols10cents' suggestion in #29) for internal consistency with "quantitative".

Since "quantitative" and "qualitative" have glossary entries, "feasible" should, too.

**Comment by laboon** [comment]
Whoops, thought it did.  Adding.

**Comment by laboon** [comment]
Addressed in commit 6c6d5f6

**Comment by laboon** [comment]
Ehh, changed the wording a bit. See commit 4b2a65a

**Comment by timparenti** [comment]
:+1:
