### ISSUE TITLE
Is test plan template immediately followed by definitions necessary?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#32]
It seems a little redundant to have the test plan template in section 6.1 with just the field names and empty space to the right of them, and then immediately repeat the field names with their definitions in section 6.1.1. Especially given that the field names are bolded in 6.1.1, I think it would be fine to just have that and leave out the blank template in 6.1... but perhaps you have a reason for this :)

**Comment by timparenti** [comment]
+1, recommend simply deleting lines 23–34 (including the "Overview of the Fields" heading). This would also have the added benefit that the numbering of the subsections within 6.1 would match the numbering in the list.

**Comment by laboon** [comment]
Oh man this makes it look so much better!  Good catch!
