### ISSUE TITLE
"logged on" sounds weird to me, possible personal problem

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#34]
In section 6.1.6, the phrase "logged on" is used twice:

> This may have been accomplished in a variety of ways: the user has never logged on before; the user is already logged on and bought any items that were in the cart, resetting the counter; 

This may just be me, but it has an association in my brain with early 90s internet terminology, like "surf the world wide web" and sounds a bit dated/out of touch. Or a bit hollywood:

<img src="http://ia.media-imdb.com/images/M/MV5BODgwMzc1MjU2MV5BMl5BanBnXkFtZTYwNjY4Nzc5._V1_UY1200_CR90,0,630,1200_AL_.jpg" alt="swordfish" />

"Logged in" would sound fine here, if you were talking about a system that a user would have to authenticate to, which may not be the case (and I'm presuming is the reason you used "logged on" instead). I'd probably say "the user has never visited the site before; the user has already visited the site" if we're talking about a web-based e-commerce system, or "the user has never used this software before; the user has already used this software" if the intent is to be more general.

Or tell me to sit on it :)

**Comment by laboon** [comment]
I meant "logged in" but apparently I have been watching too many early-90s computer movies.  
![screen shot 2015-08-22 at 2 28 02 pm](https://cloud.githubusercontent.com/assets/1417717/9425315/06d0e6ba-48da-11e5-8465-3b4a1e1eec20.png)

**Comment by laboon** [comment]
s/logged on/logged in/g in commit 86398e9

**Comment by timparenti** [comment]
You're just jealous of that 28.8 bps modem.
