### ISSUE TITLE
Suggestion for test case status example

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#35]
You might address this later in the book, or you might have decided not to address this, but what about a test case that depends upon a temporal state that we can't mock? For example, a test case that can only be run during full moons, daylight savings time switches, or in the last ten minutes of every hour?

Would this fall under the "blocked" status, if you were doing a test run at a time other than the one needed? Is this worth calling out?

**Comment by laboon** [comment]
Oh, yes!  The test plan chapter is still discussing black box testing, so I wouldn't discuss it in terms of mocks.  However, I should add something about modifying the _environment_ and making your own "real-life test doubles" (e.g., changing system time, the simple_respond gem, generating your own test data to load, etc.)

Will most likely get to this on Monday.

The first test plan I ever ran was actually all about time, and I had to mess around with the clocks of various systems... 

Thanks!
