### ISSUE TITLE
What about comparing test case runs over time? Is that a thing?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#36]
It's kind of a thing I've wanted Jenkins to do but haven't gotten it to do.

What I mean is: say we have 3 test cases and we've done 4 test runs in the last week-- 

<table>
<tr>
<th/>
<th>Test Run 1</th>
<th>Test Run 2</th>
<th>Test Run 3</th>
<th>Test Run 4</th>
</tr>
<tr>
<th>Test 1</th>
<td>F</td>
<td>P</td>
<td>P</td>
<td>P</td>
</tr>
<tr>
<th>Test 2</th>
<td>P</td>
<td>F</td>
<td>P</td>
<td>F</td>
</tr>
<tr>
<th>Test 3</th>
<td>P</td>
<td>P</td>
<td>B</td>
<td>B</td>
</tr>
</table>

F = failed, P = passed, B = blocked

So we could see that Test 1 was broken but now it's fixed, Test 2 is flaky and either the test or the functionality isn't consistently reliable, and something happened to block Test 3 two runs ago and is probably still going on.

Is this a thing that people do? Does it have a name? Is it worth talking about?

Maybe something like this will be in the "communicating with stakeholders" section. I feel like knowing the rate at which how many tests are going from failed to passed is something that could be useful to stakeholders to gauge completeness... ?

**Comment by laboon** [comment]
It is - I guess I would call it "test run tracking"?  I'd probably also want to reference git bisect at this point.  This will require a little bit of work/planning so I'm going to plan to work on it after the weekend.

This is definitely something I want the book to go into, and I discuss it in class.  Thanks for bringing it up!
