### ISSUE TITLE
Cite a source for "overweight" BMI changes

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#41]
In section 8.3, you mention:

> In 1998, tens of millions of people suddenly became overweight due to a redefinition of the term “overweight” in regards to body-mass index (BMI).

I think this deserves a link or something.

**Comment by laboon** [comment]
Will do

**Comment by laboon** [comment]
Fixed by commit aad2dfc. Thanks to this issue, I also found another place where I referenced "a study" without providing a title - fixed in commit 44e709b
