### ISSUE TITLE
Second definition for "verification" needed

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#43]
File 10, line 53, defines "verification":

> This illustrates the difference between __verification__ and __validation__.  Verification is ensuring that you're building the software right; validation is ensuring that you're building the right software.

However, file 41, line 210, offers a second definition:

> In the above instance, instead of asserting that a particular value is returned (since no value is ever returned), you instead can make a "meta-assertion" that `.haveFun()` is called.  This is called __verification__ since you are _verifying_ that a method has been called.  Note that this kind of verification has nothing to do with the kind of verification that means "checking that the software is right".  They are two different concepts that happen to share the same word.

Since it is bolded as a vocabulary word, this second definition of verification, with respect to mocks, should appear in the glossary.  It should probably be its own entry, with an appropriate parenthetical.

**Comment by laboon** [comment]
Whoops!  I actually thought I had done this.  Will add a second definition to the glossary.
