### ISSUE TITLE
Absurdly long subsection heading

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#44]
There is a bit of irony in the fact that Subsection 14.7.3, __"Unit Tests Should Have Few Assertions (Preferably Only One) And Simple, Direct Names"__ is one of the only ones without a simple and direct name.  It doesn't even fit on one line in the PDF (see page 119), and although `pdflatex` handles this fairly gracefully, it's still non-ideal.

From someone who, just five chapters earlier in 9.3.1, pokes fun at long titles such as _The Egg, Or The Memoirs Of Gregory Giddy, Esq: With The Lucubrations Of Messrs. Francis Flimsy, Frederick Florid, And Ben Bombast. To Which Are Added, The Private Opinions Of Patty Pout, Lucy Luscious, And Priscilla Positive. Also The Memoirs Of A Right Honourable Puppy. Conceived By A Celebrated Hen, And Laid Before The Public By A Famous Cock-Feeder,_ I am disappoint.

----

Other less absurd, but still too-long-to-fit-on-one-line headings include:

* Page 21: __4.1__ Equivalence Classes and Expected versus Observed Behavior
* Page 34: __5.2__ Functional versus Non-Functional Requirements (Quality Attributes)
* Page 91: __12.1__ Benefits and Drawbacks of Manual and Automated Testing
* Page 180: __20.5__ General Guidelines When Developing a Security Testing Plan

**Comment by laboon** [comment]
"Do I contradict myself?  Very well, then I contradict myself.  I am large, I contain multitudes." -Walt Whitman

But in this case, you're right. Will fix.
