### ISSUE TITLE
Setting the reader up for Ruby/Haskell love that isn't there

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#46]
File 5, line 31 says:

> I'll often mention how much easier something is to do in Ruby, or how a particular kind of defect doesn't even exist in Haskell, or other references along those lines.

which is great, and all; except... in this book, you kinda don't.  Go ahead and `grep -irn --color '\(Ruby\|Haskell\)' text` to see for yourself.

While you do mention Ruby and Haskell a few times each throughout the text, it tends to be for other reasons.  It may make sense to retool this sentence to be a bit more accurately reflective of how Ruby and Haskell are actually portrayed in this book.

Lest you be tempted to just take that sentence out altogether, I will add that I do think it's important for something to be said along these lines.

**Comment by laboon** [comment]
Yeah, I'm going to re-word it.
