### ISSUE TITLE
Drill Sergeant metaphor a bit harsh

### ISSUE THREAD

**Issue by sdzivanovich** [laboon/ebook#47]
In Section 2.1: "but it’s not going to get any stronger until someone tries to hit it with some discipline."

In this metaphor, the function is a child (based on the usage of "helicopter parent"), so it's kind of alluding to hitting a child.

**Comment by laboon** [comment]
Ugh.  You're right, that's horrible and not at all what I meant.  Will fix today.

**Comment by laboon** [comment]
Changed to 'I can nurture the poor little function, but it's not going to know what it's capable of until it experiences some discipline.'
