### ISSUE TITLE
BADREQ vs. REQ

### ISSUE THREAD

**Issue by sdzivanovich** [laboon/ebook#48]
In section 5.1, BADREQ-1 is used to label a "bad requirement", but other similarly bad requirements in the surrounding text are labeled as REQ-1 and REQ-2.

**Comment by laboon** [comment]
Good catch!  Thanks!  Will fix.

**Comment by laboon** [comment]
Standardized names of all requirements in this chapter on commit 986356db38f3c303220a097c1850d7176f36aaf4
