### ISSUE TITLE
Warn against being *too general* in defect summaries?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#52]
Section 9.3.1 about defect summaries is mostly about being too long and specific; but I think being too general could be a problem as well. If all the bugs in the list are, e.g., "search is broken", "search totally broken", "can't search", "search doesn't work", that doesn't really help much either.

**Comment by laboon** [comment]
Hmm, I thought I did this - if not, I definitely need to.  Looking into it now.

**Comment by laboon** [comment]
Ahh, I see.  I meant that the summary should be succinct, not long, but I don't mention specificity.  I will re-word.
