### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by DonKrieger** [laboon/ebook#58]
Linux ubuntu 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
pandoc 1.12.2.1  Compiled with texmath 0.6.5.2, highlighting-kate 0.5.5.1.
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian) kpathsea version 6.1.1
XeTeX 3.1415926-2.5-0.9999.3-2014012222 (TeX Live 2013/Debian) kpathsea version 6.1.1

Dump:
...pandoc text/98_glossary_of_terms.md \
		--listings --highlight-style kate \
		-o compiled_tex/98_glossary_of_terms.tex
pandoc text/99_acknowledgements.md \
		--listings --highlight-style kate \
		-o compiled_tex/99_acknowledgements.tex
pandoc main.tex -o software-testing-laboon-ebook.pdf \
		--latex-engine xelatex \
		--chapters -N --toc --toc-depth=2 \
		-M documentclass="book" \
		-M classoption="twoside" \
		-M classoption="letterpaper" \
		-M geometry="margin=1.25in" \
		-M title="\Huge{\textbf{A Friendly Introduction\\\\to Software Testing}}" \
		-M author="\LARGE{Bill Laboon}" \
		-M date="{\Large\textcopyright~\textbf{2015-08-24}}\\\\Compiled in PDF\LaTeX{}\endgraf\textit{for AKS and CKN}"
pandoc: 
Error at "source" (line 423, column 68):
unexpected "\n"
expecting "!"
  A string of non-alphabetic characters, e.g. \lstinline!78 &^\item
                                                                   ^
make: *** [pdf] Error 1

**Comment by laboon** [comment]
Hmm, I can't repro on my machine, but I am running OS X. @timparenti do you have any ideas?

**Comment by laboon** [comment]
As a substitute, @DonKrieger , there's a generated PDF at https://github.com/laboon/software-testing/blob/master/software-testing-laboon-ebook.pdf

**Comment by DonKrieger** [comment]
Hi Bill,

I’ll think about it and let you know if I find the problem.
Thanks for putting up the complete pdf which I will download later.
I think it must have worked fine for the others who’ve downloaded the book.
My installation is brand new and totally untested since I had to install pandoc, pdflatex, and xelatex to do the make.
In addition I puzzled out enough about github to clone your “whatever it’s called” and likely did it wrong enough to cause the failure.
The free software thing is wonderful but the dependency piece of it is a nightmare.

Best regards,

Don

[Signature0001]
Don Krieger, Ph.D.
Department of Neurological Surgery
University of Pittsburgh
(412)648-9654 Office
(412)521-4431 Cell/Text

**Comment by timparenti** [comment]
I notice that `pandoc` 1.12.2.1 is from December 2013.  For comparison, I am running:
* pandoc.exe 1.15.0.6 Compiled with texmath 0.8.2.2, highlighting-kate 0.6.
* pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Cygwin) kpathsea version 6.2.1
* XeTeX 3.14159265-2.6-0.99992 (TeX Live 2015/Cygwin) kpathsea version 6.2.1

In the dump above, the line in question is apparently converted to:
```latex
A string of non-alphabetic characters, e.g. \lstinline!78 &^\item
```
which is invalid LaTeX, as the `\lstinline` is not closed before the new `\item` begins.

`pandoc` 1.15.0.6, by contrast, gives the much more carefully escaped:
```latex
\item
  A string of non-alphabetic characters, e.g.
  \texttt{78\ \&\^{}\%\ 0()\ {[}{]}}
\item
```

At first glance, it would seem that something to do with escaping these special characters has been fixed in more recent versions of `pandoc`.

**Comment by laboon** [comment]
Since this looks like a versioning issue with pandoc, I'm going to close this issue.

**Comment by DonKrieger** [comment]
Hi Bill,

I agree.

I just heard from Rob and we are planning to talk about it early next week – I’m not sure when.
If you post your thoughts and timing needs to us it might help.
Have a good weekend.

Best regards,

Don

[Signature0001]
Don Krieger, Ph.D.
Department of Neurological Surgery
University of Pittsburgh
(412)648-9654 Office
(412)521-4431 Cell/Text
