### ISSUE TITLE
Math is hard

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#59]
I don't think this math is right, but I'm not sure... this is in 12.1, Benefits and Drawbacks of Manual and Automated Testing, under Benefits of Automated Testing, #8 It scales very well:

> Adding automated tests often results in a sub-linear increase in time, since much of the time for automated tests often consists of setup time. That is, adding five test cases to an existing plan consisting of ten cases may result in an execution time that is much less than twice the original test plan.

Ok. So if we start from 10 cases, and let's say each test takes a second to run, so that's 10 seconds. Scaling linearly would mean that if we add 5 cases, the test run would take 15 seconds. 15 seconds is much less than 20 (twice the original 10 seconds), but I think you're trying to say that it scales less than linearly, so it would be much less than 15 seconds, which is not twice the original 10 seconds.

If i'm understanding everything correctly, and I'm not sure about that so that's why this is an issue and not a PR, I *think* you could change this to:

> That is, adding ten test cases to an existing plan consisting of ten cases may result in an execution time that is much less than twice the original test plan.

or:

> That is, adding five test cases to an existing plan consisting of ten cases may result in an execution time that is much less than 150% of the original test plan.

Maybe???

**Comment by laboon** [comment]
This was a typo.  I meant:

> ... adding five test cases to an existing plan consisting of ~~ten~~ _five_ cases may result in an execution time that is much less than twice the original test plan.

**Comment by laboon** [comment]
Thanks!
