### ISSUE TITLE
Figure out what to do with end of 35 (automated test list)

### ISSUE THREAD

**Issue by laboon** [laboon/ebook#6]

**Comment by timparenti** [comment]
Section 12.3 ("Overview of Types of Automated Tests") lack descriptions of the different types of automated tests.  See `text/35_automated_testing.md`.

**Comment by laboon** [comment]
Since I discuss all of these later in the book, I don't think it's necessary to have a separate list of them here.  I removed that section.

**Comment by timparenti** [comment]
Removed in 44debd8efe7f9d683afd5b1b6b187765aa7c6712.
