### ISSUE TITLE
Missing benefit of unit tests-- speed

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#61]
In 13.1, in my opinion one of the biggest benefits of unit tests is missing from the list-- how friggin fast they are! You usually don't have to spend a lot of time setting up a lot of interconnected components, or opening browsers, or querying databases, or waiting on the network. The faster your tests run, the more feedback coverage you can get out of the fixed amount of time you have before you get bored waiting for your tests to finish.

**Comment by laboon** [comment]
!!! Did I not mention this?!?!  It definitely needs to be said.  Thanks!

**Comment by carols10cents** [comment]
You do have a list item for faster turnaround time, but that's explained in comparison to waiting for a build or waiting for a tester to look at it. I was hoping for a comparison to systems level tests, which the paragraph right before the list of benefits starts to hint at, but doesn't call out directly.

**Comment by laboon** [comment]
Added in commit 0df9c04
