### ISSUE TITLE
Dependency injection clarification

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#63]
In 14.1 Test Doubles, right before the `Dog` example, you say:

> In order to minimize issues, you should pass in the object as a parameter whenever possible, as opposed to relying on class-level variables or even worse, global variables.

But a bit later, you say: 

> It would be even more difficult if _df did not have a nice setter function, but instead was created
internally or only as a byproduct of an entirely different method. 

This case of creating an object internally is actually more common in my experience than relying on class-level variables or global variables and I think deserves being called out in the earlier sentence. 

Unless I'm just misunderstanding the terminology? In Ruby, the case not mentioned would be described as "instance variables" or fields or I do like the description "internally", while class-level variables are something different....?

**Comment by carols10cents** [comment]
Also, I feel like the Dog example after the "It would be even more difficult if _df did not have a nice setter function, but instead was created internally or only as a byproduct of an entirely different method." is a much better example than the example before that sentence that has `setDogFood`... the `setDogFood` way is *inconvenient* but in the second example it's *impossible* and makes for a much more powerful example. Maybe rearrange those examples so that you go from really bad -> better but inconvenient -> best?

**Comment by laboon** [comment]
Agree with the seond comment and ordering.  Will also rephrase this section a bit.

Although I (and according to Google, many many others) often call these class-level variables, that's kind of confusing.  "Member variable" is probably the best term - although these act like Ruby instance variables, I don't remember any Java shop I've worked at ever calling them "instance variables".

**Comment by laboon** [comment]
I will probably fix this (and most of the other issues) on Tuesday.  Tomorrow is the first day of class!

**Comment by laboon** [comment]
Fixed in commit dc371ce
