### ISSUE TITLE
2 different implementations of `haveFunAtDuckPond` is confusing

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#64]
So in chapter 13 Intro to Unit Testing, `haveFunAtDuckPond` is defined as:

```java
public void haveFunAtDuckPond(DuckPond duckPond) {
    System.out.println("Having fun at the duck pond");
    duckPond.haveFun();
}
```

in order to illustrate the difficulty of testing impure functions. 

Then, at the beginning of chapter 14 Advanced Unit Testing, you have this implementation of `haveFunAtDuckPond`: 

```java
public int haveFunAtDuckPond(Duck d, int numFeedings) {
    if (d == null || numFeedings <= 0) { return 0; }
    int amountOfFun = 0;
    for (int j=0; j < numFeedings; j++) {
        amountOfFun++;
        d.feed();
        d.quack();
    }
    return amountOfFun;
}
```

This one has a return value in addition to some side effects.

THEN, later in chapter 14 in section 14.3 on Mocks and Verification, it says:

> "Yes, yes, this is all fine," I can hear you saying, "but you didn't answer the original question!  We are still dependent on asserting on a value that is returned from a method, and thus won't be able to test methods without a return value!"  Remember the method that we wanted to test from earlier in the chapter:

```java
public class Person {

    public void haveFunAtDuckPond(DuckPond duckPond) {
        duckPond.haveFun();
    }

}
```

> There is no return value and thus nothing on which to assert.

So for one thing, this implementation is not from earlier in *this* chapter, it's from earlier in the book or from the previous chapter.

For another thing, the intervening reimplementation of `haveFunAtDuckPond` between this reference and its antecedent is confusing... which one am I supposed to be remembering? Why are there 2? 

I'd consider making them be two separate concepts entirely and only have one implementation of `haveFunAtDuckPond` in the book, even though in the real world there are multiple ways one could have fun at a duck pond (not stepping in duck poop is my definition of having fun at a duck pond ;)

**Comment by timparenti** [comment]
The reference to "earlier in the chapter" is a holdover from when these two chapters were one.  That said, I agree with the rest of this; the two competing implementations are confusing.

Maybe one of them could become something like  `enjoyCatCafe`? ;)

**Comment by laboon** [comment]
Tim is right, this was originally one huge chapter.  When it was refactored, I missed this.

Also, not sure why I love having fun at duck ponds so much, but I like Tim's idea of just changing to `enjoyCatCafe`.

**Comment by timparenti** [comment]
Upon further consideration, the concept of a cat café may be needlessly difficult for readers whose native language is not English (and even for some whose is!). But there are plenty of other ways you can convey enjoying the company of some sort of animal in some sort of environment.

**Comment by laboon** [comment]
I'm going to go with cat cafe.  I'll add a parenthetical note on what a cat cafe is.

**Comment by laboon** [comment]
Removed one duck pond in commit 786755d
