### ISSUE TITLE
Distinguish between before/after method ordering and test ordering

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#65]
In this paragraph in 14.4 setup and teardown, I feel like 2 different concepts are being muddled:

> Also note that while there is nothing stopping you from prefacing multiple methods with `@Before` or `@After` annotations, it's usually not necessary and will just make it more difficult to follow the code.  If you do make multiple methods with these annotations, they will run in a deterministic order (that is, if you run it again, they will run in the same order).  However, since tests should not depend upon each other, this ordering is not specified and is liable to change whenever you update your code and/or JUnit version.  It is possible to specify the order that tests will run in, using the `@FixMethodOrder` annotation, but you want to avoid doing that if at all possible.  Honestly, I feel a little guilty even writing down that it is possible.

You're discussing first *the order in which multiple before/after methods run* and then you switch to talking about *the order that tests will run in*. Maybe these are the same thing in jUnit? But I don't think they are, since the "deterministic order" describes the before/after methods as running in the same order if you run the tests again, whereas I hope jUnit is randomizing the order in which the tests run differently for every test run, otherwise it would be less likely that you'd see failures due to a dependence on a test ordering?

So if you use the `@FixMethodOrder` annotation, will that affect the order of the before/after methods too or not? I can't tell from what you've said here. 

I think the test ordering could be left out here and perhaps discussed elsewhere instead... or perhaps just leave this whole paragraph at "Also note that while there is nothing stopping you from prefacing multiple methods with `@Before` or `@After` annotations, it's usually not necessary and will just make it more difficult to follow the code."?

**Comment by laboon** [comment]
Agreed.  I will at least re-phrase.  `@FixMethodOrder` is something that I have had to do in the past, but it probably isn't relevant for an "intro" book (at least not in any detail).

**Comment by carols10cents** [comment]
Ah, I just got to section "14.7.4 Unit Tests Should Be Independent", which is a much more thorough explanation of *test* ordering, so I think mention of it here could be taken out for clarity of the before/after method ordering issue.

**Comment by laboon** [comment]
Yup yup, fixed in 34781f3
