### ISSUE TITLE
Additional argument against testing private methods: inhibits refactoring

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#66]
My personal argument against testing private methods is missing from the flame war presented; I can only assume this is an oversight ;)

IMO, the reason you use private methods is so that you reserve the right to, in the future, aggressively refactor the internals of that class and change all the private methods around willy-nilly. If you add tests for your private methods, though, you've now created a barrier to that refactoring-- you're either going to have to update all those tests or you did work that you're going to delete when you refactor.

**Comment by laboon** [comment]
YES can't believe I didn't say that!

**Comment by laboon** [comment]
address in 699c178

**Comment by laboon** [comment]
s/address/addressed
