### ISSUE TITLE
Consider condensing or dropping section on testing private methods in java?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#67]
Advanced unit testing chapter 14 spends a lot of time building up to how to test private methods in java using reflection, and I'm not sure that it merits that much inclusion in the context of the whole book.

4.5 pages out of 211 is a full 2% of the book (and I didn't even exclude the cover pages or glossaries, so it's an even higher percentage of the actual text). The section meanders through explaining what reflection is, takes a detour through code that only works for public methods, mentions that we've basically implemented a REPL (and then has to explain what REPLs are and why they're useful, which is neat but not particularly relevant), and then gets back to actually testing private methods. And all this for something that in the previous section, you said you mostly didn't recommend unless the existing code meant you had no other choice!

This is also pretty language-specific in a book that claimed in the beginning to be using Java just as something that's pretty universal that everyone could figure out. It's in stark contrast to the other concepts in this chapter like doubles, stubs, mocks, setup, etc that are generalizable.

However, if this is a concept/question that comes up in class that you spend time on and people find worthwhile, I could see justification for leaving it in. This *is* the Advanced Unit Testing chapter, after all... 

Maybe condense this section to just the last example `testPrivateLaboonify` and a light explanation? Or relegate this whole section to an appendix? I wouldn't shed tears if it was gone completely though ;)

**Comment by laboon** [comment]
Yeah, this was just something lots of students had trouble with or wanted to know about.  I will condense and move it to an appendix.  Thanks!

**Comment by timparenti** [comment]
Just another reason I actually need to figure out how to get the `\appendix` construct to work within the `pandoc` workflow…

**Comment by timparenti** [comment]
I do think, though, that whereas other chapters tend to have clear, articulable, and often singular objectives, this one (even split from its predecessor) seems more like it's trying to do it all. Apart from addressing the length issues this chapter has had since #11 (it's still the largest by far), I think this would also contribute to its cohesion in that sense. Another split is probably not necessary, but it could be considered in the context of this change.

**Comment by laboon** [comment]
Moved to a separate supplemental chapter, as well as updated pandoc and whatnot, in commit cca2db8

I may go back to this chapter and futz with it some more later.
