### ISSUE TITLE
ARGH FINISH STOCHASTIC TESTING!

### ISSUE THREAD

**Issue by laboon** [laboon/ebook#7]

**Comment by timparenti** [comment]
Subsections 17.2.2–17.2.4 (in Section 17.2, "Property-Based Testing") are empty:

* QuickCheck
* Using QuickCheck for Checking A Java Method
* Benefits and Drawbacks

See `text/67_stochastic_testing.md`.

**Comment by laboon** [comment]
Filled in some monkeys. May add more based on review comments, but done for now.

Commit: 533037935a1e7f44e0b3e3db94f6ccc064751d01
