### ISSUE TITLE
Tautological tests not as bad as tests that don't test what you think they're testing

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#75]
Something has been bugging me about the emphasis on tautological tests and I couldn't really articulate it until I was working and hit the situation I was trying to describe but couldn't!

> 13.3.4 Ensuring that Tests are Testing What You Expect
>
> One of the simplest ways to do this is to first ensure that your tests fail! While we’ll go into detail on a development strategy that always calls for tests to fail first in the chapter on TDD, a quick change to a test can often prove that it’s not just passing all the time because you’re mistakenly asserting that true == true, for example.
>
> In the linked list equality test above, what could you change to ensure that your tests are testing what you think they are testing?
> 
> ...
>
> In all of these instances, the test should fail. You can then rest a little easier, knowing that your test isn’t tautological (always passing, no matter what the code does).

So this section *is* called "Ensuring that Tests are Testing What You Expect", which I like and think is important. But it mentions twice that the thing that you're looking for is:

> a quick change to a test can often prove that it’s not just passing all the time because you’re mistakenly asserting that true == true, for example.
> ...
> You can then rest a little easier, knowing that your test isn’t tautological (always passing, no matter what the code does).

I don't think tautological test cases are as common as *not testing what i think i'm testing* (for me at least). Here's what I mean:

* I get a bug report that says "User gets error E when they are in situation X and do Y".
* I look into the problem and I think I've fixed it.
* I write a test:

        doSetup(X);
        do(Y);
        assertNoError();

* The test passes! Ship it!
* Close bug
* Bug gets reopened, users are still seeing the error :(

And the cause of this is *my test was setting up the normal happy path, not situation X*! I'm testing *something*, just not what I want to be. It's not tautologically saying "assert(true)" though-- this test *would* break if the happy path broke.

What I've now learned to do instead is:

* I get a bug report that says "User gets error E when they are in situation X and do Y".
* I write a test:

        doSetup(X);
        do(Y);
        assertNoError();

* **Run the test and fix the setup and the doing until the test fails because I'm getting error E, thus making sure that I've reproduced this situation exactly**
* I look into the problem and I think I've fixed it.
* The test passes! Ship it!
* Close bug
* Bug stays closed (until we find a new situation X) ;)

Tautological tests are also mentioned in:

> 15.1 What is TDD?
> Test-Driven Development is a software development methodology that comprises several key points:
> 1. Writing tests first, before code: Before you even start thinking of how to do something, this forces you to think of what is to be done. Since your code has not been written, you can check that the test initially fails (in order to avoid tautological tests which always pass), and have a specific goal that you are reaching toward (getting the test you just wrote to pass).

And:
> 15.5 Benefits of TDD
> ...
> Yet another benefit is that the tests that you write with TDD are relevant, since new tests must fail first (ensuring that the test is not redundant) and must pass before the cycle of writing a piece of code is considered “complete”. You are less likely in this case to write tests which are unnecessary or tautological, or over-test one area and under-test another.
> 
> If you are writing tests after the fact, it’s easy to fall into the trap of assuming that what the program does is what the program should do. However, remember that tests are supposed to check expected behavior against the observed behavior. If you are “expecting” something that you already
“observed”, your tests run the risk of being tautological!

I feel like *testing what you think you're testing* is more important and common than *preventing tautological tests* or *preventing redundant tests* and should be emphasized more in these spots than they are currently. WDYT?

**Comment by carols10cents** [comment]
[This article in RubyWeekly is an interesting example that reminded me of this](http://blog.arkency.com/2015/09/testing-race-conditions/?utm_source=rubyweekly&utm_medium=email) -- it's about testing race conditions, that you don't oversell something when there's a whole bunch of people trying to buy the last thing. The author mentions it's really important to see this test fail to make sure you're actually producing enough concurrency to be testing this situation.

**Comment by laboon** [comment]
Yes, will do this today.  Don't know why tautological tests were so stuck in my head but not the more common issue.

**Comment by laboon** [comment]
By "today" I meant "next year" but added in commit 500da59
