### ISSUE TITLE
Resources / further reading section

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#79]
These are a few related works that I was reminded of that I think would work nicely in a "further reading" section-- in addition to all the works you mentioned throughout. I don't think you mentioned any of these, though:

* [Explore it!](https://pragprog.com/book/ehxta/explore-it), pragprog book on exploratory testing
* [The RSpec Book](https://pragprog.com/book/achbd/the-rspec-book) is still one of the best in-depth intros to TDD that I've seen
* [Growing Object-Oriented Software, Guided by Tests](http://www.growing-object-oriented-software.com/), affectionately known as "GOOS"
* [Computer Related Risks](http://www.amazon.com/Computer-Related-Risks-Peter-G-Neumann/dp/020155805X/ref=sr_1_1?ie=UTF8&qid=1441487010&sr=8-1&keywords=programming+related+risks) - didn't I lend you my copy of this? I lent it to someone, I think. It has a bunch of case studies, including the Therac-25 which you did mention.

**Comment by laboon** [comment]
I still have your copy of Risks, I will return it to you this coming Friday if you'll be at the office.

**Comment by laboon** [comment]
Adding this section!  BTW I will come to the office and drop off your Risks book on Monday.  I'll be downtown that morning anyways.

**Comment by laboon** [comment]
Started this with commit a879b26 - still have lots to add!

**Comment by laboon** [comment]
Added some more, including the ones you mentioned, in commit b469754d6a86994a9f45e00d07a96124215b18c0
