### ISSUE TITLE
"Why Test Software?" chapter (file 13) is incomplete.

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#8]
Sections 3.3–3.6 (in Chapter 3, "Why Test Software?") are incomplete:

* Catching Bugs Sooner Rather than Later
* Metrics
* Business Sense
* Ensuring Quality

See `text/13_why_test_software.md`.

**Comment by timparenti** [comment]
Good thing I caught this sooner, rather than later.  :stuck_out_tongue_winking_eye:

**Comment by laboon** [comment]
:wink: Filled it in like a madman on commit f270db143d2394a797e5529c9b15d648af2b48bc
