### ISSUE TITLE
Integrity/responsibility in context of interacting with stakeholders

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#81]
So there's a situation I've seen play out in real life many times that I think could be a worthwhile addition to the chapter on interacting with stakeholders. You mention situations where the tester finds a small issue, and the manager sees that while it looks small, it has wider implications-- but what I've seen more often is the opposite. A tester finds a big issue, often late in the process with a deadline looming, and the manager then seeks to minimize or dismiss the issue in order to keep the project on schedule.

This could be only a little bit ethically questionable; maybe the problem only affects a few customers and the manager knows it can be fixed soon after the deadline. They use their judgment, however questionable we may think it is, to decide it's not worth communicating more widely.

But it could be more of a problem, e.g.

* everyone's private information is viewable
* it's definitely possible to control a car's systems through the on-board wifi connection
* the demo works fine but any real-world use of the system crashes immediately
* the marketing material makes claims that the software can do something that it definitely cannot do

You tell your manager, and they say "the deadline must be met; we're not going to address this". 

What do you as a software tester have a professional responsibility to do in that situation?

Perhaps this is getting too deep and too much into the "what is good?" philosophical realm, but... I feel like as a reviewer of this book, I have a responsibility to suggest to you that this is a topic your readers should be aware of :)

**Comment by laboon** [comment]
No, definitely.  This is a priority for me to add before we discuss stakeholder interaction in class.

**Comment by laboon** [comment]
Put in a few paragraphs addressing this.  Sadly, I think full coverage of the topic would be its own book.

Commit 918123e
