### ISSUE TITLE
Distinguish between hacker and cracker?

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#82]
Just remembered I meant to file this when reading the security chapter and didn't. 

Starting in the Penetration Testing section, you use the term "cracker" but haven't defined it or explained why you're using that where CNN would probably use the term "hacker". I know the difference, but not everyone will. 

I think a short mention of the difference would fit well near the beginning of the chapter where you mention Steven Levy's book "Hackers" and phone phreaks.

**Comment by laboon** [comment]
Mentioned and explained! commit cae3811
