### ISSUE TITLE
Ensure correspondence between bolded words in the text and entries in the glossary

### ISSUE THREAD

**Issue by carols10cents** [laboon/ebook#83]
IMO, all bolded words in the text should appear in the glossary, and all terms defined in the glossary should appear in the book (and be bolded on an appropriate early usage). This is not currently the case, for example:

* **Sploit** is defined in the glossary but not used anywhere in the text (a PR is coming in a few minutes that removes this from the glossary)
* **Undefined** is bolded in the Testing Basics chapter but not defined in the glossary.

These can be found by searching for `__` in the text and doing an XOR with the terms in the glossary.

I thought about doing this but then decided that 1. you should decide if you even want this as an explicit goal 2. it's probably worth writing a little shell script to do so that can be rerun quickly as the book changes.

**Comment by laboon** [comment]
It's definitely an explicit goal.  I should have made a shell script to do it already.  Thanks!

**Comment by laboon** [comment]
Added def in 41eb28cfa9dfee7b4de4b69df9c464ede3d48d77

**Comment by timparenti** [comment]
@laboon Does this mean you've checked all entries for correspondence?  Or just the ones listed in this issue?

**Comment by laboon** [comment]
Just this specific one.  I'll file a new issue to write the script.
