### ISSUE TITLE
Distinguish when you do care about performance, but with a different frame-of-reference.

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#85]
File 70, line 7, reads, in part:
> The supercomputer has several orders of magnitude longer response time than the video game, but does this mean the supercomputer is less performant than your video game console?  On the particular __performance indicator__ of response time, one could argue yes, but that performance indicator was not considered very important to the developers of the weather forecasting system.

It may not actually be the case that response time isn't an important performance indicator for the developers of the weather forecasting system; rather, it's more likely that they have a different metric altogether for what is considered a "timely" response.

If this is the National Hurricane Center, for example, it could be quite critical in terms of public safety that the forecast, even if it takes half an hour to produce, be ready for release on-time.  Whereas, at your typical Field Office, it's not generally a matter of life-and-death if it takes fifteen extra minutes to generate the latest version of the long-range forecast.

Since this leads into different types of performance indicators and why you would use them, this text should probably make a bit more clear of a distinction between (1) the case that you don't care, and (2) the case that you _do_ care, just somehow differently.

**Comment by laboon** [comment]
Good point.  Re-worded and moved some discussion of this into the KPI section in commit d0c105c
