### ISSUE TITLE
Consistently present concepts, benefits, and drawbacks

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#90]
* Section 11.1 is called "Concepts, Benefits, and Drawbacks".
* Section 12.1 puts benefits and drawbacks together; Sections 15.5–6 have them separately.
* Section 15.3 is just called "Concepts".  Concepts of what?

Consider making the structure of these sections more consistent.

**Comment by laboon** [comment]
Changed the structure a bit in a7df664
