### ISSUE TITLE
Duplicate or ambiguous section names

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#91]
Several section names are either duplicated or ambiguous as they stand:

* Section 2.1 is merely called "What is It?" while several other sections are more descriptively called "What is _____?".  This is complicated by the fact that its parent, Chapter 2, is one of these ("What is Software Testing?").
* Section 16.9 and Chapter 22 are both called "Conclusion".
* Subsection 21.4.1 is merely called "Example", while Section 15.4 is more descriptively called "Example: Building FizzBuzz via TDD".
 
There are also two other cases which are probably okay, given their context within Section 6.1 (The Basic Layout of a Test Plan) and Section 13.3 (Turning Our Example Into a Unit Test):

* Subsections 6.1.3 and 13.3.1 are both called "Preconditions".
* Subsections 6.1.5 and 13.3.2 are both called "Execution Steps".

**Comment by laboon** [comment]
Yeah, I couldn't come up with a great subsection heading for 2.1, but it's at least better than repetition.  Changed 16.9 and 21.4.1 to be more specific. I think the other two cases are fine. Fixed in commit 63ffcc3
