### ISSUE TITLE
Bibles?

### ISSUE THREAD

**Issue by timparenti** [laboon/ebook#93]
File 13, line 56 refers to Steve McConnell's _Code Complete_ as "[o]ne of the bibles of software engineering."  Although the use of lowercase-B "bibles" is correct in a secular context such as this, I wonder whether the religious connotation is appropriate to include in the first place.  It has the potential to alienate both those who believe in a capital-B Bible and those who don't.

**Comment by laboon** [comment]
That's certainly possible.  I rephrased it as "one of the most well-regarded books on software engineering..." in commit ad73e3c
