### ISSUE TITLE
Details on Fakes

### ISSUE THREAD

**Issue by laboon** [laboon/ebook#97]
(from Joel)

I spent a little bit of time looking through this.

One thing I noticed was a specific treatment of fake objects, which I
think is incomplete.

If you look at: http://xunitpatterns.com/Fake%20Object.html

You'll notice that fake objects are treated in a specific way, and are
themselves very interesting from a testers perspective.

Just something I thought I'd want to point out -- I'm sensitive to
this because I think "fakes" in this sense are very powerful and
under-utilized.

**Comment by laboon** [comment]
Added in a section on Fakes @joelmccracken - f23f425ffd071ca3231a24c23300aebb9936a535

(formatting and whatnot fixed in a subsequent commit)

**Comment by joelmccracken** [comment]
<3 it!
